### ISSUE TITLE
Why are we hiding the first child in menu?

### ISSUE THREAD

**Issue by nstriedinger** [massgov/mayflower-patternlab#294]
Please explain?

![screen shot 2017-01-11 at 2 03 17 pm](https://cloud.githubusercontent.com/assets/231467/21862339/c7ec9576-d806-11e6-82c6-6fa57e93aac6.png)

**Comment by gender404** [comment]
It is only hidden on Wide screens.  On narrow screens, it is displayed in the submenu.  This is due to the dual functionality of the main link.  On wide screens, clicking the main link takes you to that page.  On narrow screens, clicking this link just opens the sub menu.  So on narrow screens we needed an extra link in submenu to take the user to the main page.
